### ISSUE TITLE
Text cursor not working in Firefox

### ISSUE THREAD

**Issue by valp124** [os-js/osjs-textpad-application#2]
If you open an existing file in textpad on Firefox, it seems like it's impossible to place a cursor anywhere, and typing is only possible at the very end of the file. On Chrome it works just fine though.

**Comment by andersevenrud** [comment]
Indeed! I was able to reproduce. Text is editable, but cannot place the cursor anywhere (changed title to reflect this).

Investigating now.

**Comment by andersevenrud** [comment]
This issue actually seems to go a bit deeper than the textpad application.

Initial findings shows that this is related to CSS in the actual Textarea GUI component(s).  It's the same on a regular text field.

I've opened an issue here: https://github.com/os-js/osjs-gui/issues/18

I'll get back to you and close this issue when I have this fixed.

**Comment by andersevenrud** [comment]
If you run `npm update @osjs/gui` and `npm run build` in your OS.js installation this issue should now be resolved.

**Comment by valp124** [comment]
You're fast as always, man! 👍 🥇

**Comment by andersevenrud** [comment]
You caught me just in the right time. I was finishing up some other OS.js stuff, hehe :smile: 

Thanks for reporting this though. This has probably been an issue for quite some time....

Let me know if it works out and close this issue.

**Comment by valp124** [comment]
👍 👍

**Comment by valp124** [comment]
Tested in FF, works like a charm now!

**Comment by andersevenrud** [comment]
Awesome!
